<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="WKWZTPqvmdckJHX" failures="0" tests="7" name="com.qa.caltrate.fr.test.CaltrateFRGeleesCaltrateTest" time="66.699" errors="1" timestamp="2023-02-10T11:31:14 IST" skipped="0">
  <testcase classname="com.qa.caltrate.fr.test.CaltrateFRGeleesCaltrateTest" name="verifyBreadcrumbOne" time="5.162"/>
  <system-out/>
  <testcase classname="com.qa.caltrate.fr.test.CaltrateFRGeleesCaltrateTest" name="verifyBreadcrumbTwo" time="3.824"/>
  <system-out/>
  <testcase classname="com.qa.caltrate.fr.test.CaltrateFRGeleesCaltrateTest" name="verifyBreadcrumbThree" time="1.894"/>
  <system-out/>
  <testcase classname="com.qa.caltrate.fr.test.CaltrateFRGeleesCaltrateTest" name="verifyAcheter" time="23.421">
    <error message="Acheter button is not closed" type="java.lang.Exception">
      <![CDATA[java.lang.Exception: Acheter button is not closed
at com.qa.caltrate.fr.pages.CaltrateFRGeleesCaltratePage.clickAcheterBtn(CaltrateFRGeleesCaltratePage.java:83)
at com.qa.caltrate.fr.test.CaltrateFRGeleesCaltrateTest.verifyAcheter(CaltrateFRGeleesCaltrateTest.java:68)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- verifyAcheter -->
  <system-out/>
  <testcase classname="com.qa.caltrate.fr.test.CaltrateFRGeleesCaltrateTest" name="verifycoupon" time="12.404"/>
  <system-out/>
  <testcase classname="com.qa.caltrate.fr.test.CaltrateFRGeleesCaltrateTest" name="verifyProduits" time="3.771"/>
  <system-out/>
  <testcase classname="com.qa.caltrate.fr.test.CaltrateFRGeleesCaltrateTest" name="verifySaveNowImg" time="16.223"/>
  <system-out/>
</testsuite> <!-- com.qa.caltrate.fr.test.CaltrateFRGeleesCaltrateTest -->
