<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="WKWZTPqvmdckJHX" failures="5" tests="31" name="com.qa.sensodyne.us.test.SensodyneCompleteProtectionExtraFreshTest" time="683.934" errors="0" timestamp="2023-01-09T05:28:28 IST" skipped="15">
  <testcase classname="com.qa.sensodyne.us.test.SensodyneCompleteProtectionExtraFreshTest" name="cookieButton" time="28.211"/>
  <system-out/>
  <testcase classname="com.qa.sensodyne.us.test.SensodyneCompleteProtectionExtraFreshTest" name="verifyWriteAReview" time="13.122"/>
  <system-out/>
  <testcase classname="com.qa.sensodyne.us.test.SensodyneCompleteProtectionExtraFreshTest" name="verifyBuyNowOne" time="10.995"/>
  <system-out/>
  <testcase classname="com.qa.sensodyne.us.test.SensodyneCompleteProtectionExtraFreshTest" name="verifyGetCoupon" time="19.864"/>
  <system-out/>
  <testcase classname="com.qa.sensodyne.us.test.SensodyneCompleteProtectionExtraFreshTest" name="verifyOriginal" time="27.570"/>
  <system-out/>
  <testcase classname="com.qa.sensodyne.us.test.SensodyneCompleteProtectionExtraFreshTest" name="verifyBreadCrumb" time="22.189"/>
  <system-out/>
  <testcase classname="com.qa.sensodyne.us.test.SensodyneCompleteProtectionExtraFreshTest" name="verifyIngredients" time="10.234"/>
  <system-out/>
  <testcase classname="com.qa.sensodyne.us.test.SensodyneCompleteProtectionExtraFreshTest" name="verifyDirections" time="10.379"/>
  <system-out/>
  <testcase classname="com.qa.sensodyne.us.test.SensodyneCompleteProtectionExtraFreshTest" name="verifyWarnings" time="9.471"/>
  <system-out/>
  <testcase classname="com.qa.sensodyne.us.test.SensodyneCompleteProtectionExtraFreshTest" name="verifyMostPopularProductsOne" time="26.368">
    <skipped/>
  </testcase> <!-- verifyMostPopularProductsOne -->
  <system-out/>
  <testcase classname="com.qa.sensodyne.us.test.SensodyneCompleteProtectionExtraFreshTest" name="verifyMostPopularProductsOne" time="21.293">
    <failure message="expected [products/sensodyne-rapid-relief-mint-toothpaste/] but found [products/sensodyne-rapid-relief-mint-toothpaste/?rapid_relief]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [products/sensodyne-rapid-relief-mint-toothpaste/] but found [products/sensodyne-rapid-relief-mint-toothpaste/?rapid_relief]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at com.qa.baseClass.BaseClass.compareTwoText(BaseClass.java:762)
at com.qa.sensodyne.us.test.SensodyneCompleteProtectionExtraFreshTest.verifyMostPopularProductsOne(SensodyneCompleteProtectionExtraFreshTest.java:139)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- verifyMostPopularProductsOne -->
  <system-out/>
  <testcase classname="com.qa.sensodyne.us.test.SensodyneCompleteProtectionExtraFreshTest" name="verifyMostPopularProductsOne" time="22.920">
    <skipped/>
  </testcase> <!-- verifyMostPopularProductsOne -->
  <system-out/>
  <testcase classname="com.qa.sensodyne.us.test.SensodyneCompleteProtectionExtraFreshTest" name="verifyMostPopularProductsOne" time="22.294">
    <skipped/>
  </testcase> <!-- verifyMostPopularProductsOne -->
  <system-out/>
  <testcase classname="com.qa.sensodyne.us.test.SensodyneCompleteProtectionExtraFreshTest" name="verifyMostPopularProductsTwo" time="23.746">
    <skipped/>
  </testcase> <!-- verifyMostPopularProductsTwo -->
  <system-out/>
  <testcase classname="com.qa.sensodyne.us.test.SensodyneCompleteProtectionExtraFreshTest" name="verifyMostPopularProductsTwo" time="28.011">
    <skipped/>
  </testcase> <!-- verifyMostPopularProductsTwo -->
  <system-out/>
  <testcase classname="com.qa.sensodyne.us.test.SensodyneCompleteProtectionExtraFreshTest" name="verifyMostPopularProductsTwo" time="24.875">
    <skipped/>
  </testcase> <!-- verifyMostPopularProductsTwo -->
  <system-out/>
  <testcase classname="com.qa.sensodyne.us.test.SensodyneCompleteProtectionExtraFreshTest" name="verifyMostPopularProductsTwo" time="23.095">
    <failure message="expected [products/sensodyne-extra-whitening-toothpaste/] but found [products/sensodyne-extra-whitening-toothpaste/?extra_whitening]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [products/sensodyne-extra-whitening-toothpaste/] but found [products/sensodyne-extra-whitening-toothpaste/?extra_whitening]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at com.qa.baseClass.BaseClass.compareTwoText(BaseClass.java:762)
at com.qa.sensodyne.us.test.SensodyneCompleteProtectionExtraFreshTest.verifyMostPopularProductsTwo(SensodyneCompleteProtectionExtraFreshTest.java:151)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- verifyMostPopularProductsTwo -->
  <system-out/>
  <testcase classname="com.qa.sensodyne.us.test.SensodyneCompleteProtectionExtraFreshTest" name="verifyMostPopularProductsThree" time="23.710">
    <skipped/>
  </testcase> <!-- verifyMostPopularProductsThree -->
  <system-out/>
  <testcase classname="com.qa.sensodyne.us.test.SensodyneCompleteProtectionExtraFreshTest" name="verifyMostPopularProductsThree" time="25.941">
    <skipped/>
  </testcase> <!-- verifyMostPopularProductsThree -->
  <system-out/>
  <testcase classname="com.qa.sensodyne.us.test.SensodyneCompleteProtectionExtraFreshTest" name="verifyMostPopularProductsThree" time="21.566">
    <failure message="expected [products/sensodyne-repair-protect-whitening-toothpaste/] but found [products/sensodyne-repair-protect-whitening-toothpaste/?repair_protect]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [products/sensodyne-repair-protect-whitening-toothpaste/] but found [products/sensodyne-repair-protect-whitening-toothpaste/?repair_protect]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at com.qa.baseClass.BaseClass.compareTwoText(BaseClass.java:762)
at com.qa.sensodyne.us.test.SensodyneCompleteProtectionExtraFreshTest.verifyMostPopularProductsThree(SensodyneCompleteProtectionExtraFreshTest.java:163)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- verifyMostPopularProductsThree -->
  <system-out/>
  <testcase classname="com.qa.sensodyne.us.test.SensodyneCompleteProtectionExtraFreshTest" name="verifyMostPopularProductsThree" time="24.725">
    <skipped/>
  </testcase> <!-- verifyMostPopularProductsThree -->
  <system-out/>
  <testcase classname="com.qa.sensodyne.us.test.SensodyneCompleteProtectionExtraFreshTest" name="verifyMostPopularProductsFour" time="24.141">
    <failure message="expected [products/sensodyne-complete-protection-extra-fresh-toothpaste/] but found [products/sensodyne-complete-protection-extra-fresh-toothpaste/?complete_protection]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [products/sensodyne-complete-protection-extra-fresh-toothpaste/] but found [products/sensodyne-complete-protection-extra-fresh-toothpaste/?complete_protection]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at com.qa.baseClass.BaseClass.compareTwoText(BaseClass.java:762)
at com.qa.sensodyne.us.test.SensodyneCompleteProtectionExtraFreshTest.verifyMostPopularProductsFour(SensodyneCompleteProtectionExtraFreshTest.java:175)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- verifyMostPopularProductsFour -->
  <system-out/>
  <testcase classname="com.qa.sensodyne.us.test.SensodyneCompleteProtectionExtraFreshTest" name="verifyMostPopularProductsFour" time="22.739">
    <skipped/>
  </testcase> <!-- verifyMostPopularProductsFour -->
  <system-out/>
  <testcase classname="com.qa.sensodyne.us.test.SensodyneCompleteProtectionExtraFreshTest" name="verifyMostPopularProductsFour" time="28.762">
    <skipped/>
  </testcase> <!-- verifyMostPopularProductsFour -->
  <system-out/>
  <testcase classname="com.qa.sensodyne.us.test.SensodyneCompleteProtectionExtraFreshTest" name="verifyMostPopularProductsFour" time="25.240">
    <skipped/>
  </testcase> <!-- verifyMostPopularProductsFour -->
  <system-out/>
  <testcase classname="com.qa.sensodyne.us.test.SensodyneCompleteProtectionExtraFreshTest" name="verifyMostPopularProductsFive" time="24.248">
    <skipped/>
  </testcase> <!-- verifyMostPopularProductsFive -->
  <system-out/>
  <testcase classname="com.qa.sensodyne.us.test.SensodyneCompleteProtectionExtraFreshTest" name="verifyMostPopularProductsFive" time="23.830">
    <failure message="expected [products/sensodyne-fresh-mint-toothpaste/] but found [products/sensodyne-fresh-mint-toothpaste/?fresh_mint]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [products/sensodyne-fresh-mint-toothpaste/] but found [products/sensodyne-fresh-mint-toothpaste/?fresh_mint]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at com.qa.baseClass.BaseClass.compareTwoText(BaseClass.java:762)
at com.qa.sensodyne.us.test.SensodyneCompleteProtectionExtraFreshTest.verifyMostPopularProductsFive(SensodyneCompleteProtectionExtraFreshTest.java:187)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- verifyMostPopularProductsFive -->
  <system-out/>
  <testcase classname="com.qa.sensodyne.us.test.SensodyneCompleteProtectionExtraFreshTest" name="verifyMostPopularProductsFive" time="24.032">
    <skipped/>
  </testcase> <!-- verifyMostPopularProductsFive -->
  <system-out/>
  <testcase classname="com.qa.sensodyne.us.test.SensodyneCompleteProtectionExtraFreshTest" name="verifyMostPopularProductsFive" time="28.787">
    <skipped/>
  </testcase> <!-- verifyMostPopularProductsFive -->
  <system-out/>
  <testcase classname="com.qa.sensodyne.us.test.SensodyneCompleteProtectionExtraFreshTest" name="verifyGetYourCoupon" time="19.335"/>
  <system-out/>
  <testcase classname="com.qa.sensodyne.us.test.SensodyneCompleteProtectionExtraFreshTest" name="verifyFindYourStore" time="22.241"/>
  <system-out/>
</testsuite> <!-- com.qa.sensodyne.us.test.SensodyneCompleteProtectionExtraFreshTest -->
