<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="WKWZTPqvmdckJHX" failures="2" tests="24" name="com.qa.voltarengel.test.VoltarengelWristTest" time="359.152" errors="2" timestamp="2023-04-23T23:50:50 IST" skipped="8">
  <testcase classname="com.qa.voltarengel.test.VoltarengelWristTest" name="cookieButton" time="9.038"/>
  <system-out/>
  <testcase classname="com.qa.voltarengel.test.VoltarengelWristTest" name="verifyBreadcrumbOne" time="13.307"/>
  <system-out/>
  <testcase classname="com.qa.voltarengel.test.VoltarengelWristTest" name="verifyBreadcrumbTwo" time="13.520"/>
  <system-out/>
  <testcase classname="com.qa.voltarengel.test.VoltarengelWristTest" name="verifyBreadcrumbThree" time="10.508"/>
  <system-out/>
  <testcase classname="com.qa.voltarengel.test.VoltarengelWristTest" name="verifyBreadcrumbFour" time="9.941"/>
  <system-out/>
  <testcase classname="com.qa.voltarengel.test.VoltarengelWristTest" name="verifyHyperLinkADayJob" time="15.023">
    <skipped/>
  </testcase> <!-- verifyHyperLinkADayJob -->
  <system-out/>
  <testcase classname="com.qa.voltarengel.test.VoltarengelWristTest" name="verifyHyperLinkADayJob" time="10.930">
    <failure message="expected [living-with-arthritis/managing-arthritis/work/] but found [https://www.voltarengel.com/living-with-arthritis/managing-arthritis/work/]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [living-with-arthritis/managing-arthritis/work/] but found [https://www.voltarengel.com/living-with-arthritis/managing-arthritis/work/]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at com.qa.baseClass.BaseClass.compareTwoText(BaseClass.java:812)
at com.qa.voltarengel.test.VoltarengelWristTest.verifyHyperLinkADayJob(VoltarengelWristTest.java:99)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- verifyHyperLinkADayJob -->
  <system-out/>
  <testcase classname="com.qa.voltarengel.test.VoltarengelWristTest" name="verifyHyperLinkADayJob" time="8.651">
    <skipped/>
  </testcase> <!-- verifyHyperLinkADayJob -->
  <system-out/>
  <testcase classname="com.qa.voltarengel.test.VoltarengelWristTest" name="verifyHyperLinkArthritisPain" time="11.513"/>
  <system-out/>
  <testcase classname="com.qa.voltarengel.test.VoltarengelWristTest" name="verifyHyperLinkVoltarenArthritisPainGel" time="16.156">
    <skipped/>
  </testcase> <!-- verifyHyperLinkVoltarenArthritisPainGel -->
  <system-out/>
  <testcase classname="com.qa.voltarengel.test.VoltarengelWristTest" name="verifyHyperLinkVoltarenArthritisPainGel" time="14.679">
    <skipped/>
  </testcase> <!-- verifyHyperLinkVoltarenArthritisPainGel -->
  <system-out/>
  <testcase classname="com.qa.voltarengel.test.VoltarengelWristTest" name="verifyHyperLinkVoltarenArthritisPainGel" time="15.676">
    <failure message="expected [what-is-voltaren/] but found [https://www.voltarengel.com/what-is-voltaren/]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [what-is-voltaren/] but found [https://www.voltarengel.com/what-is-voltaren/]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at com.qa.baseClass.BaseClass.compareTwoText(BaseClass.java:812)
at com.qa.voltarengel.test.VoltarengelWristTest.verifyHyperLinkVoltarenArthritisPainGel(VoltarengelWristTest.java:123)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- verifyHyperLinkVoltarenArthritisPainGel -->
  <system-out/>
  <testcase classname="com.qa.voltarengel.test.VoltarengelWristTest" name="verifyHyperLinkJointPain" time="11.221"/>
  <system-out/>
  <testcase classname="com.qa.voltarengel.test.VoltarengelWristTest" name="verifyHyperLinkArthritisExercise" time="9.037"/>
  <system-out/>
  <testcase classname="com.qa.voltarengel.test.VoltarengelWristTest" name="verifyHyperLinkHelpDecreaseYourArthritisPain" time="12.167"/>
  <system-out/>
  <testcase classname="com.qa.voltarengel.test.VoltarengelWristTest" name="verifyShowReference" time="6.359"/>
  <system-out/>
  <testcase classname="com.qa.voltarengel.test.VoltarengelWristTest" name="verifyRelatedArticleReadMoreOne" time="23.669">
    <skipped/>
  </testcase> <!-- verifyRelatedArticleReadMoreOne -->
  <system-out/>
  <testcase classname="com.qa.voltarengel.test.VoltarengelWristTest" name="verifyRelatedArticleReadMoreOne" time="25.860">
    <skipped/>
  </testcase> <!-- verifyRelatedArticleReadMoreOne -->
  <system-out/>
  <testcase classname="com.qa.voltarengel.test.VoltarengelWristTest" name="verifyRelatedArticleReadMoreOne" time="24.845">
    <error message="Related Article Read More One is not preseneted in the page" type="java.lang.Exception">
      <![CDATA[java.lang.Exception: Related Article Read More One is not preseneted in the page
at com.qa.voltarengel.pages.VoltarengelWristPage.clickRelatedArticleReadMoreOne(VoltarengelWristPage.java:297)
at com.qa.voltarengel.test.VoltarengelWristTest.verifyRelatedArticleReadMoreOne(VoltarengelWristTest.java:176)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- verifyRelatedArticleReadMoreOne -->
  <system-out/>
  <testcase classname="com.qa.voltarengel.test.VoltarengelWristTest" name="verifyRelatedArticleReadMoreTwo" time="26.721">
    <error message="Related Article Read More Two is not preseneted in the page" type="java.lang.Exception">
      <![CDATA[java.lang.Exception: Related Article Read More Two is not preseneted in the page
at com.qa.voltarengel.pages.VoltarengelWristPage.clickRelatedArticleReadMoreTwo(VoltarengelWristPage.java:310)
at com.qa.voltarengel.test.VoltarengelWristTest.verifyRelatedArticleReadMoreTwo(VoltarengelWristTest.java:188)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- verifyRelatedArticleReadMoreTwo -->
  <system-out/>
  <testcase classname="com.qa.voltarengel.test.VoltarengelWristTest" name="verifyRelatedArticleReadMoreTwo" time="25.986">
    <skipped/>
  </testcase> <!-- verifyRelatedArticleReadMoreTwo -->
  <system-out/>
  <testcase classname="com.qa.voltarengel.test.VoltarengelWristTest" name="verifyRelatedArticleReadMoreTwo" time="24.415">
    <skipped/>
  </testcase> <!-- verifyRelatedArticleReadMoreTwo -->
  <system-out/>
  <testcase classname="com.qa.voltarengel.test.VoltarengelWristTest" name="verifyGetCoupons" time="12.285"/>
  <system-out/>
  <testcase classname="com.qa.voltarengel.test.VoltarengelWristTest" name="verifyBuyNow" time="7.645"/>
  <system-out/>
</testsuite> <!-- com.qa.voltarengel.test.VoltarengelWristTest -->
