<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="WKWZTPqvmdckJHX" failures="0" tests="9" name="com.qa.abreva.test.AbrevaHydrateChappedLipsTest" time="159.992" errors="1" timestamp="2023-05-16T23:32:44 IST" skipped="2">
  <testcase classname="com.qa.abreva.test.AbrevaHydrateChappedLipsTest" name="cookieButton" time="9.239"/>
  <system-out/>
  <testcase classname="com.qa.abreva.test.AbrevaHydrateChappedLipsTest" name="verifyBreadcrumbOne" time="17.603"/>
  <system-out/>
  <testcase classname="com.qa.abreva.test.AbrevaHydrateChappedLipsTest" name="verifyWholeCardSecOne" time="14.843"/>
  <system-out/>
  <testcase classname="com.qa.abreva.test.AbrevaHydrateChappedLipsTest" name="verifyWholeCardSecTwo" time="15.206"/>
  <system-out/>
  <testcase classname="com.qa.abreva.test.AbrevaHydrateChappedLipsTest" name="verifyWholeCardSecThree" time="15.217"/>
  <system-out/>
  <testcase classname="com.qa.abreva.test.AbrevaHydrateChappedLipsTest" name="verifyTakeAQuiz" time="27.498">
    <skipped/>
  </testcase> <!-- verifyTakeAQuiz -->
  <system-out/>
  <testcase classname="com.qa.abreva.test.AbrevaHydrateChappedLipsTest" name="verifyTakeAQuiz" time="24.165">
    <error message="Take A Quiz is not presented in the page" type="java.lang.Exception">
      <![CDATA[java.lang.Exception: Take A Quiz is not presented in the page
at com.qa.abreva.pages.AbrevaHydrateChappedLipsPage.clickTakeAQuiz(AbrevaHydrateChappedLipsPage.java:141)
at com.qa.abreva.test.AbrevaHydrateChappedLipsTest.verifyTakeAQuiz(AbrevaHydrateChappedLipsTest.java:93)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- verifyTakeAQuiz -->
  <system-out/>
  <testcase classname="com.qa.abreva.test.AbrevaHydrateChappedLipsTest" name="verifyTakeAQuiz" time="27.820">
    <skipped/>
  </testcase> <!-- verifyTakeAQuiz -->
  <system-out/>
  <testcase classname="com.qa.abreva.test.AbrevaHydrateChappedLipsTest" name="verifyBuyNow" time="8.401"/>
  <system-out/>
</testsuite> <!-- com.qa.abreva.test.AbrevaHydrateChappedLipsTest -->
