<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="WKWZTPqvmdckJHX" failures="2" tests="23" name="com.qa.voltarengel.test.VoltarengelJointPainMedicineTest" time="357.139" errors="3" timestamp="2023-04-23T23:50:50 IST" skipped="10">
  <testcase classname="com.qa.voltarengel.test.VoltarengelJointPainMedicineTest" name="cookieButton" time="7.174"/>
  <system-out/>
  <testcase classname="com.qa.voltarengel.test.VoltarengelJointPainMedicineTest" name="verifyBreadcrumbOne" time="11.597"/>
  <system-out/>
  <testcase classname="com.qa.voltarengel.test.VoltarengelJointPainMedicineTest" name="verifyBreadcrumbTwo" time="10.525"/>
  <system-out/>
  <testcase classname="com.qa.voltarengel.test.VoltarengelJointPainMedicineTest" name="verifyBreadcrumbThree" time="24.905">
    <error message="Breadcrumb Three is not presented in the page" type="java.lang.Exception">
      <![CDATA[java.lang.Exception: Breadcrumb Three is not presented in the page
at com.qa.voltarengel.pages.VoltarengelJointPainMedicinePage.clickBreadcrumbThree(VoltarengelJointPainMedicinePage.java:165)
at com.qa.voltarengel.test.VoltarengelJointPainMedicineTest.verifyBreadcrumbThree(VoltarengelJointPainMedicineTest.java:70)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- verifyBreadcrumbThree -->
  <system-out/>
  <testcase classname="com.qa.voltarengel.test.VoltarengelJointPainMedicineTest" name="verifyBreadcrumbThree" time="23.560">
    <skipped/>
  </testcase> <!-- verifyBreadcrumbThree -->
  <system-out/>
  <testcase classname="com.qa.voltarengel.test.VoltarengelJointPainMedicineTest" name="verifyBreadcrumbThree" time="25.298">
    <skipped/>
  </testcase> <!-- verifyBreadcrumbThree -->
  <system-out/>
  <testcase classname="com.qa.voltarengel.test.VoltarengelJointPainMedicineTest" name="verifyHyperLinkVoltarenArthritisPainGel" time="11.515"/>
  <system-out/>
  <testcase classname="com.qa.voltarengel.test.VoltarengelJointPainMedicineTest" name="verifyHyperLinkAdvil" time="24.071">
    <error message="Hyper Link Advil is not preseneted in the page" type="java.lang.Exception">
      <![CDATA[java.lang.Exception: Hyper Link Advil is not preseneted in the page
at com.qa.voltarengel.pages.VoltarengelJointPainMedicinePage.clickHyperLinkAdvil(VoltarengelJointPainMedicinePage.java:192)
at com.qa.voltarengel.test.VoltarengelJointPainMedicineTest.verifyHyperLinkAdvil(VoltarengelJointPainMedicineTest.java:95)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- verifyHyperLinkAdvil -->
  <system-out/>
  <testcase classname="com.qa.voltarengel.test.VoltarengelJointPainMedicineTest" name="verifyHyperLinkAdvil" time="24.434">
    <skipped/>
  </testcase> <!-- verifyHyperLinkAdvil -->
  <system-out/>
  <testcase classname="com.qa.voltarengel.test.VoltarengelJointPainMedicineTest" name="verifyHyperLinkAdvil" time="24.793">
    <skipped/>
  </testcase> <!-- verifyHyperLinkAdvil -->
  <system-out/>
  <testcase classname="com.qa.voltarengel.test.VoltarengelJointPainMedicineTest" name="verifyHyperLinkAboutPain" time="8.332"/>
  <system-out/>
  <testcase classname="com.qa.voltarengel.test.VoltarengelJointPainMedicineTest" name="verifyHyperLinkManagingYourArthritisSymptoms" time="9.515"/>
  <system-out/>
  <testcase classname="com.qa.voltarengel.test.VoltarengelJointPainMedicineTest" name="verifyShowReference" time="4.350"/>
  <system-out/>
  <testcase classname="com.qa.voltarengel.test.VoltarengelJointPainMedicineTest" name="verifyRelatedArticleReadMoreOne" time="10.604">
    <skipped/>
  </testcase> <!-- verifyRelatedArticleReadMoreOne -->
  <system-out/>
  <testcase classname="com.qa.voltarengel.test.VoltarengelJointPainMedicineTest" name="verifyRelatedArticleReadMoreOne" time="9.258">
    <skipped/>
  </testcase> <!-- verifyRelatedArticleReadMoreOne -->
  <system-out/>
  <testcase classname="com.qa.voltarengel.test.VoltarengelJointPainMedicineTest" name="verifyRelatedArticleReadMoreOne" time="8.676">
    <failure message="expected [living-with-arthritis/natural-remedies/] but found [https://www.voltarengel.com/living-with-arthritis/natural-remedies/]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [living-with-arthritis/natural-remedies/] but found [https://www.voltarengel.com/living-with-arthritis/natural-remedies/]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at com.qa.baseClass.BaseClass.compareTwoText(BaseClass.java:812)
at com.qa.voltarengel.test.VoltarengelJointPainMedicineTest.verifyRelatedArticleReadMoreOne(VoltarengelJointPainMedicineTest.java:146)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- verifyRelatedArticleReadMoreOne -->
  <system-out/>
  <testcase classname="com.qa.voltarengel.test.VoltarengelJointPainMedicineTest" name="verifyRelatedArticleReadMoreTwo" time="11.742">
    <failure message="expected [what-is-arthritis/symptoms/] but found [https://www.voltarengel.com/what-is-arthritis/symptoms/]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [what-is-arthritis/symptoms/] but found [https://www.voltarengel.com/what-is-arthritis/symptoms/]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at com.qa.baseClass.BaseClass.compareTwoText(BaseClass.java:812)
at com.qa.voltarengel.test.VoltarengelJointPainMedicineTest.verifyRelatedArticleReadMoreTwo(VoltarengelJointPainMedicineTest.java:158)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- verifyRelatedArticleReadMoreTwo -->
  <system-out/>
  <testcase classname="com.qa.voltarengel.test.VoltarengelJointPainMedicineTest" name="verifyRelatedArticleReadMoreTwo" time="10.639">
    <skipped/>
  </testcase> <!-- verifyRelatedArticleReadMoreTwo -->
  <system-out/>
  <testcase classname="com.qa.voltarengel.test.VoltarengelJointPainMedicineTest" name="verifyRelatedArticleReadMoreTwo" time="9.673">
    <skipped/>
  </testcase> <!-- verifyRelatedArticleReadMoreTwo -->
  <system-out/>
  <testcase classname="com.qa.voltarengel.test.VoltarengelJointPainMedicineTest" name="verifyGetCoupons" time="7.069"/>
  <system-out/>
  <testcase classname="com.qa.voltarengel.test.VoltarengelJointPainMedicineTest" name="verifyBuyNow" time="25.557">
    <skipped/>
  </testcase> <!-- verifyBuyNow -->
  <system-out/>
  <testcase classname="com.qa.voltarengel.test.VoltarengelJointPainMedicineTest" name="verifyBuyNow" time="23.726">
    <skipped/>
  </testcase> <!-- verifyBuyNow -->
  <system-out/>
  <testcase classname="com.qa.voltarengel.test.VoltarengelJointPainMedicineTest" name="verifyBuyNow" time="30.126">
    <error message="Buy Now Button is not Presented in the page" type="java.lang.Exception">
      <![CDATA[java.lang.Exception: Buy Now Button is not Presented in the page
at com.qa.voltarengel.pages.VoltarengelJointPainMedicinePage.clickBuyNow(VoltarengelJointPainMedicinePage.java:90)
at com.qa.voltarengel.test.VoltarengelJointPainMedicineTest.verifyBuyNow(VoltarengelJointPainMedicineTest.java:177)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- verifyBuyNow -->
  <system-out/>
</testsuite> <!-- com.qa.voltarengel.test.VoltarengelJointPainMedicineTest -->
