<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="WKWZTPqvmdckJHX" failures="2" tests="11" name="com.qa.abreva.test.AbrevaUsingMyFsaOrHsaToPurchaseTest" time="196.288" errors="1" timestamp="2023-05-16T23:32:44 IST" skipped="6">
  <testcase classname="com.qa.abreva.test.AbrevaUsingMyFsaOrHsaToPurchaseTest" name="cookieButton" time="4.696"/>
  <system-out/>
  <testcase classname="com.qa.abreva.test.AbrevaUsingMyFsaOrHsaToPurchaseTest" name="verifyHyperLinkAbrevaProducts" time="10.765">
    <skipped/>
  </testcase> <!-- verifyHyperLinkAbrevaProducts -->
  <system-out/>
  <testcase classname="com.qa.abreva.test.AbrevaUsingMyFsaOrHsaToPurchaseTest" name="verifyHyperLinkAbrevaProducts" time="11.646">
    <failure message="expected [cold-sore-products/abreva-cream/] but found [https://www.abreva.com/cold-sore-products/abreva-cream/]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [cold-sore-products/abreva-cream/] but found [https://www.abreva.com/cold-sore-products/abreva-cream/]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at com.qa.baseClass.BaseClass.compareTwoText(BaseClass.java:822)
at com.qa.abreva.test.AbrevaUsingMyFsaOrHsaToPurchaseTest.verifyHyperLinkAbrevaProducts(AbrevaUsingMyFsaOrHsaToPurchaseTest.java:51)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- verifyHyperLinkAbrevaProducts -->
  <system-out/>
  <testcase classname="com.qa.abreva.test.AbrevaUsingMyFsaOrHsaToPurchaseTest" name="verifyHyperLinkAbrevaProducts" time="18.144">
    <skipped/>
  </testcase> <!-- verifyHyperLinkAbrevaProducts -->
  <system-out/>
  <testcase classname="com.qa.abreva.test.AbrevaUsingMyFsaOrHsaToPurchaseTest" name="verifyHyperLinkFaqPage" time="14.255">
    <skipped/>
  </testcase> <!-- verifyHyperLinkFaqPage -->
  <system-out/>
  <testcase classname="com.qa.abreva.test.AbrevaUsingMyFsaOrHsaToPurchaseTest" name="verifyHyperLinkFaqPage" time="33.850">
    <failure message="expected [faq/abreva-basics/] but found [https://www.abreva.com/faq/abreva-basics/]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [faq/abreva-basics/] but found [https://www.abreva.com/faq/abreva-basics/]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at com.qa.baseClass.BaseClass.compareTwoText(BaseClass.java:822)
at com.qa.abreva.test.AbrevaUsingMyFsaOrHsaToPurchaseTest.verifyHyperLinkFaqPage(AbrevaUsingMyFsaOrHsaToPurchaseTest.java:63)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- verifyHyperLinkFaqPage -->
  <system-out/>
  <testcase classname="com.qa.abreva.test.AbrevaUsingMyFsaOrHsaToPurchaseTest" name="verifyHyperLinkFaqPage" time="20.988">
    <skipped/>
  </testcase> <!-- verifyHyperLinkFaqPage -->
  <system-out/>
  <testcase classname="com.qa.abreva.test.AbrevaUsingMyFsaOrHsaToPurchaseTest" name="verifyGetcoupon" time="22.588">
    <skipped/>
  </testcase> <!-- verifyGetcoupon -->
  <system-out/>
  <testcase classname="com.qa.abreva.test.AbrevaUsingMyFsaOrHsaToPurchaseTest" name="verifyGetcoupon" time="25.733">
    <error message="HyperLink Get coupon is not presented in the page" type="java.lang.Exception">
      <![CDATA[java.lang.Exception: HyperLink Get coupon is not presented in the page
at com.qa.abreva.pages.AbrevaUsingMyFsaOrHsaToPurchasePage.clickGetcoupon(AbrevaUsingMyFsaOrHsaToPurchasePage.java:102)
at com.qa.abreva.test.AbrevaUsingMyFsaOrHsaToPurchaseTest.verifyGetcoupon(AbrevaUsingMyFsaOrHsaToPurchaseTest.java:70)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- verifyGetcoupon -->
  <system-out/>
  <testcase classname="com.qa.abreva.test.AbrevaUsingMyFsaOrHsaToPurchaseTest" name="verifyGetcoupon" time="27.087">
    <skipped/>
  </testcase> <!-- verifyGetcoupon -->
  <system-out/>
  <testcase classname="com.qa.abreva.test.AbrevaUsingMyFsaOrHsaToPurchaseTest" name="verifyBuyNow" time="6.536"/>
  <system-out/>
</testsuite> <!-- com.qa.abreva.test.AbrevaUsingMyFsaOrHsaToPurchaseTest -->
